// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/parsing/v1/parsing.proto

package parsingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOffersRequest) Reset() {
	*x = SyncOffersRequest{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOffersRequest) ProtoMessage() {}

func (x *SyncOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOffersRequest.ProtoReflect.Descriptor instead.
func (*SyncOffersRequest) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{0}
}

type SyncOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOffersResponse) Reset() {
	*x = SyncOffersResponse{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOffersResponse) ProtoMessage() {}

func (x *SyncOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOffersResponse.ProtoReflect.Descriptor instead.
func (*SyncOffersResponse) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{1}
}

func (x *SyncOffersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncOffersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	State         *int64                 `protobuf:"varint,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
	AppId         *int64                 `protobuf:"varint,4,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	NameQuery     *string                `protobuf:"bytes,5,opt,name=name_query,json=nameQuery,proto3,oneof" json:"name_query,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,6,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,7,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	ListTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=list_time,json=listTime,proto3,oneof" json:"list_time,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3,oneof" json:"last_updated,omitempty"`
	SortBy        *string                `protobuf:"bytes,10,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortOrder     *string                `protobuf:"bytes,11,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersRequest) Reset() {
	*x = ListOffersRequest{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersRequest) ProtoMessage() {}

func (x *ListOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersRequest.ProtoReflect.Descriptor instead.
func (*ListOffersRequest) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{2}
}

func (x *ListOffersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOffersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOffersRequest) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *ListOffersRequest) GetAppId() int64 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *ListOffersRequest) GetNameQuery() string {
	if x != nil && x.NameQuery != nil {
		return *x.NameQuery
	}
	return ""
}

func (x *ListOffersRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListOffersRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListOffersRequest) GetListTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ListTime
	}
	return nil
}

func (x *ListOffersRequest) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *ListOffersRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListOffersRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

type Offer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price            float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Commission       float64                `protobuf:"fixed64,3,opt,name=commission,proto3" json:"commission,omitempty"`
	Tax              float64                `protobuf:"fixed64,4,opt,name=tax,proto3" json:"tax,omitempty"`
	ClassId          string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	InstanceId       string                 `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AppId            int64                  `protobuf:"varint,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ContextId        string                 `protobuf:"bytes,8,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	AssetId          string                 `protobuf:"bytes,9,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Name             string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	OfferId          string                 `protobuf:"bytes,11,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	State            int64                  `protobuf:"varint,12,opt,name=state,proto3" json:"state,omitempty"`
	EscrowEndDate    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=escrow_end_date,json=escrowEndDate,proto3" json:"escrow_end_date,omitempty"`
	ListTime         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=list_time,json=listTime,proto3" json:"list_time,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Wear             float64                `protobuf:"fixed64,16,opt,name=wear,proto3" json:"wear,omitempty"`
	Txid             string                 `protobuf:"bytes,17,opt,name=txid,proto3" json:"txid,omitempty"`
	TradeLocked      bool                   `protobuf:"varint,18,opt,name=trade_locked,json=tradeLocked,proto3" json:"trade_locked,omitempty"`
	Addons           []string               `protobuf:"bytes,19,rep,name=addons,proto3" json:"addons,omitempty"`
	BuyerCountryCode string                 `protobuf:"bytes,20,opt,name=buyer_country_code,json=buyerCountryCode,proto3" json:"buyer_country_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{3}
}

func (x *Offer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offer) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *Offer) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Offer) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Offer) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Offer) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Offer) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Offer) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Offer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Offer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Offer) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Offer) GetEscrowEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EscrowEndDate
	}
	return nil
}

func (x *Offer) GetListTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ListTime
	}
	return nil
}

func (x *Offer) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Offer) GetWear() float64 {
	if x != nil {
		return x.Wear
	}
	return 0
}

func (x *Offer) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Offer) GetTradeLocked() bool {
	if x != nil {
		return x.TradeLocked
	}
	return false
}

func (x *Offer) GetAddons() []string {
	if x != nil {
		return x.Addons
	}
	return nil
}

func (x *Offer) GetBuyerCountryCode() string {
	if x != nil {
		return x.BuyerCountryCode
	}
	return ""
}

type ListOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Offer               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersResponse) Reset() {
	*x = ListOffersResponse{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersResponse) ProtoMessage() {}

func (x *ListOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersResponse.ProtoReflect.Descriptor instead.
func (*ListOffersResponse) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{4}
}

func (x *ListOffersResponse) GetItems() []*Offer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOffersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOffersResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOffersResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_proto_parsing_v1_parsing_proto protoreflect.FileDescriptor

const file_proto_parsing_v1_parsing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/parsing/v1/parsing.proto\x12\n" +
	"parsing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11SyncOffersRequest\"H\n" +
	"\x12SyncOffersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9e\x04\n" +
	"\x11ListOffersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x19\n" +
	"\x05state\x18\x03 \x01(\x03H\x00R\x05state\x88\x01\x01\x12\x1a\n" +
	"\x06app_id\x18\x04 \x01(\x03H\x01R\x05appId\x88\x01\x01\x12\"\n" +
	"\n" +
	"name_query\x18\x05 \x01(\tH\x02R\tnameQuery\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x06 \x01(\x01H\x03R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\a \x01(\x01H\x04R\bmaxPrice\x88\x01\x01\x12<\n" +
	"\tlist_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x05R\blistTime\x88\x01\x01\x12B\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vlastUpdated\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\n" +
	" \x01(\tH\aR\x06sortBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\v \x01(\tH\bR\tsortOrder\x88\x01\x01B\b\n" +
	"\x06_stateB\t\n" +
	"\a_app_idB\r\n" +
	"\v_name_queryB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\f\n" +
	"\n" +
	"_list_timeB\x0f\n" +
	"\r_last_updatedB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"\xfe\x04\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"commission\x18\x03 \x01(\x01R\n" +
	"commission\x12\x10\n" +
	"\x03tax\x18\x04 \x01(\x01R\x03tax\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06app_id\x18\a \x01(\x03R\x05appId\x12\x1d\n" +
	"\n" +
	"context_id\x18\b \x01(\tR\tcontextId\x12\x19\n" +
	"\basset_id\x18\t \x01(\tR\aassetId\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x19\n" +
	"\boffer_id\x18\v \x01(\tR\aofferId\x12\x14\n" +
	"\x05state\x18\f \x01(\x03R\x05state\x12B\n" +
	"\x0fescrow_end_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rescrowEndDate\x127\n" +
	"\tlist_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blistTime\x12=\n" +
	"\flast_updated\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x12\n" +
	"\x04wear\x18\x10 \x01(\x01R\x04wear\x12\x12\n" +
	"\x04txid\x18\x11 \x01(\tR\x04txid\x12!\n" +
	"\ftrade_locked\x18\x12 \x01(\bR\vtradeLocked\x12\x16\n" +
	"\x06addons\x18\x13 \x03(\tR\x06addons\x12,\n" +
	"\x12buyer_country_code\x18\x14 \x01(\tR\x10buyerCountryCode\"\x81\x01\n" +
	"\x12ListOffersResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.parsing.v1.OfferR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset2\xaa\x01\n" +
	"\x0eParsingService\x12K\n" +
	"\n" +
	"SyncOffers\x12\x1d.parsing.v1.SyncOffersRequest\x1a\x1e.parsing.v1.SyncOffersResponse\x12K\n" +
	"\n" +
	"ListOffers\x12\x1d.parsing.v1.ListOffersRequest\x1a\x1e.parsing.v1.ListOffersResponseB/Z-skinbaron-analyzer/proto/parsing/v1;parsingv1b\x06proto3"

var (
	file_proto_parsing_v1_parsing_proto_rawDescOnce sync.Once
	file_proto_parsing_v1_parsing_proto_rawDescData []byte
)

func file_proto_parsing_v1_parsing_proto_rawDescGZIP() []byte {
	file_proto_parsing_v1_parsing_proto_rawDescOnce.Do(func() {
		file_proto_parsing_v1_parsing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsing_v1_parsing_proto_rawDesc), len(file_proto_parsing_v1_parsing_proto_rawDesc)))
	})
	return file_proto_parsing_v1_parsing_proto_rawDescData
}

var file_proto_parsing_v1_parsing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_parsing_v1_parsing_proto_goTypes = []any{
	(*SyncOffersRequest)(nil),     // 0: parsing.v1.SyncOffersRequest
	(*SyncOffersResponse)(nil),    // 1: parsing.v1.SyncOffersResponse
	(*ListOffersRequest)(nil),     // 2: parsing.v1.ListOffersRequest
	(*Offer)(nil),                 // 3: parsing.v1.Offer
	(*ListOffersResponse)(nil),    // 4: parsing.v1.ListOffersResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_parsing_v1_parsing_proto_depIdxs = []int32{
	5, // 0: parsing.v1.ListOffersRequest.list_time:type_name -> google.protobuf.Timestamp
	5, // 1: parsing.v1.ListOffersRequest.last_updated:type_name -> google.protobuf.Timestamp
	5, // 2: parsing.v1.Offer.escrow_end_date:type_name -> google.protobuf.Timestamp
	5, // 3: parsing.v1.Offer.list_time:type_name -> google.protobuf.Timestamp
	5, // 4: parsing.v1.Offer.last_updated:type_name -> google.protobuf.Timestamp
	3, // 5: parsing.v1.ListOffersResponse.items:type_name -> parsing.v1.Offer
	0, // 6: parsing.v1.ParsingService.SyncOffers:input_type -> parsing.v1.SyncOffersRequest
	2, // 7: parsing.v1.ParsingService.ListOffers:input_type -> parsing.v1.ListOffersRequest
	1, // 8: parsing.v1.ParsingService.SyncOffers:output_type -> parsing.v1.SyncOffersResponse
	4, // 9: parsing.v1.ParsingService.ListOffers:output_type -> parsing.v1.ListOffersResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_parsing_v1_parsing_proto_init() }
func file_proto_parsing_v1_parsing_proto_init() {
	if File_proto_parsing_v1_parsing_proto != nil {
		return
	}
	file_proto_parsing_v1_parsing_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsing_v1_parsing_proto_rawDesc), len(file_proto_parsing_v1_parsing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parsing_v1_parsing_proto_goTypes,
		DependencyIndexes: file_proto_parsing_v1_parsing_proto_depIdxs,
		MessageInfos:      file_proto_parsing_v1_parsing_proto_msgTypes,
	}.Build()
	File_proto_parsing_v1_parsing_proto = out.File
	file_proto_parsing_v1_parsing_proto_goTypes = nil
	file_proto_parsing_v1_parsing_proto_depIdxs = nil
}
