// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: proto/parsing/v1/parsing.proto

package parsingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParsingService_SyncOffers_FullMethodName = "/parsing.v1.ParsingService/SyncOffers"
	ParsingService_ListOffers_FullMethodName = "/parsing.v1.ParsingService/ListOffers"
)

// ParsingServiceClient is the client API for ParsingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParsingServiceClient interface {
	SyncOffers(ctx context.Context, in *SyncOffersRequest, opts ...grpc.CallOption) (*SyncOffersResponse, error)
	ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error)
}

type parsingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParsingServiceClient(cc grpc.ClientConnInterface) ParsingServiceClient {
	return &parsingServiceClient{cc}
}

func (c *parsingServiceClient) SyncOffers(ctx context.Context, in *SyncOffersRequest, opts ...grpc.CallOption) (*SyncOffersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncOffersResponse)
	err := c.cc.Invoke(ctx, ParsingService_SyncOffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parsingServiceClient) ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOffersResponse)
	err := c.cc.Invoke(ctx, ParsingService_ListOffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParsingServiceServer is the server API for ParsingService service.
// All implementations must embed UnimplementedParsingServiceServer
// for forward compatibility.
type ParsingServiceServer interface {
	SyncOffers(context.Context, *SyncOffersRequest) (*SyncOffersResponse, error)
	ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error)
	mustEmbedUnimplementedParsingServiceServer()
}

// UnimplementedParsingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParsingServiceServer struct{}

func (UnimplementedParsingServiceServer) SyncOffers(context.Context, *SyncOffersRequest) (*SyncOffersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncOffers not implemented")
}
func (UnimplementedParsingServiceServer) ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOffers not implemented")
}
func (UnimplementedParsingServiceServer) mustEmbedUnimplementedParsingServiceServer() {}
func (UnimplementedParsingServiceServer) testEmbeddedByValue()                        {}

// UnsafeParsingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParsingServiceServer will
// result in compilation errors.
type UnsafeParsingServiceServer interface {
	mustEmbedUnimplementedParsingServiceServer()
}

func RegisterParsingServiceServer(s grpc.ServiceRegistrar, srv ParsingServiceServer) {
	// If the following call panics, it indicates UnimplementedParsingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParsingService_ServiceDesc, srv)
}

func _ParsingService_SyncOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsingServiceServer).SyncOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParsingService_SyncOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsingServiceServer).SyncOffers(ctx, req.(*SyncOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParsingService_ListOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsingServiceServer).ListOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParsingService_ListOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsingServiceServer).ListOffers(ctx, req.(*ListOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParsingService_ServiceDesc is the grpc.ServiceDesc for ParsingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParsingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parsing.v1.ParsingService",
	HandlerType: (*ParsingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncOffers",
			Handler:    _ParsingService_SyncOffers_Handler,
		},
		{
			MethodName: "ListOffers",
			Handler:    _ParsingService_ListOffers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/parsing/v1/parsing.proto",
}
