// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/parsing/v1/parsing.proto

package parsingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	State         *int64                 `protobuf:"varint,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
	AppId         *int64                 `protobuf:"varint,4,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	NameQuery     *string                `protobuf:"bytes,5,opt,name=name_query,json=nameQuery,proto3,oneof" json:"name_query,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,6,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,7,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	ListTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=list_time,json=listTime,proto3,oneof" json:"list_time,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3,oneof" json:"last_updated,omitempty"`
	SortBy        *string                `protobuf:"bytes,10,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortOrder     *string                `protobuf:"bytes,11,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersRequest) Reset() {
	*x = ListOffersRequest{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersRequest) ProtoMessage() {}

func (x *ListOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersRequest.ProtoReflect.Descriptor instead.
func (*ListOffersRequest) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{0}
}

func (x *ListOffersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOffersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOffersRequest) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *ListOffersRequest) GetAppId() int64 {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return 0
}

func (x *ListOffersRequest) GetNameQuery() string {
	if x != nil && x.NameQuery != nil {
		return *x.NameQuery
	}
	return ""
}

func (x *ListOffersRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListOffersRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListOffersRequest) GetListTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ListTime
	}
	return nil
}

func (x *ListOffersRequest) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *ListOffersRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListOffersRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

type Offer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price            float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Commission       float64                `protobuf:"fixed64,3,opt,name=commission,proto3" json:"commission,omitempty"`
	Tax              float64                `protobuf:"fixed64,4,opt,name=tax,proto3" json:"tax,omitempty"`
	ClassId          string                 `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	InstanceId       string                 `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AppId            int64                  `protobuf:"varint,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ContextId        string                 `protobuf:"bytes,8,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	AssetId          string                 `protobuf:"bytes,9,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Name             string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	OfferId          string                 `protobuf:"bytes,11,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	State            int64                  `protobuf:"varint,12,opt,name=state,proto3" json:"state,omitempty"`
	EscrowEndDate    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=escrow_end_date,json=escrowEndDate,proto3" json:"escrow_end_date,omitempty"`
	ListTime         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=list_time,json=listTime,proto3" json:"list_time,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Wear             float64                `protobuf:"fixed64,16,opt,name=wear,proto3" json:"wear,omitempty"`
	Txid             string                 `protobuf:"bytes,17,opt,name=txid,proto3" json:"txid,omitempty"`
	TradeLocked      bool                   `protobuf:"varint,18,opt,name=trade_locked,json=tradeLocked,proto3" json:"trade_locked,omitempty"`
	Addons           []string               `protobuf:"bytes,19,rep,name=addons,proto3" json:"addons,omitempty"`
	BuyerCountryCode string                 `protobuf:"bytes,20,opt,name=buyer_country_code,json=buyerCountryCode,proto3" json:"buyer_country_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{1}
}

func (x *Offer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Offer) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *Offer) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Offer) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Offer) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Offer) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Offer) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Offer) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Offer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Offer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Offer) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Offer) GetEscrowEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EscrowEndDate
	}
	return nil
}

func (x *Offer) GetListTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ListTime
	}
	return nil
}

func (x *Offer) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Offer) GetWear() float64 {
	if x != nil {
		return x.Wear
	}
	return 0
}

func (x *Offer) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *Offer) GetTradeLocked() bool {
	if x != nil {
		return x.TradeLocked
	}
	return false
}

func (x *Offer) GetAddons() []string {
	if x != nil {
		return x.Addons
	}
	return nil
}

func (x *Offer) GetBuyerCountryCode() string {
	if x != nil {
		return x.BuyerCountryCode
	}
	return ""
}

type ListOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Offer               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffersResponse) Reset() {
	*x = ListOffersResponse{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersResponse) ProtoMessage() {}

func (x *ListOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersResponse.ProtoReflect.Descriptor instead.
func (*ListOffersResponse) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{2}
}

func (x *ListOffersResponse) GetItems() []*Offer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOffersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOffersResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOffersResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListItemSalesStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ItemNameQuery *string                `protobuf:"bytes,3,opt,name=item_name_query,json=itemNameQuery,proto3,oneof" json:"item_name_query,omitempty"`
	WearName      *string                `protobuf:"bytes,4,opt,name=wear_name,json=wearName,proto3,oneof" json:"wear_name,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	SoldFrom      *string                `protobuf:"bytes,7,opt,name=sold_from,json=soldFrom,proto3,oneof" json:"sold_from,omitempty"`
	SoldTo        *string                `protobuf:"bytes,8,opt,name=sold_to,json=soldTo,proto3,oneof" json:"sold_to,omitempty"`
	MinSalesCount *int64                 `protobuf:"varint,9,opt,name=min_sales_count,json=minSalesCount,proto3,oneof" json:"min_sales_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemSalesStatsRequest) Reset() {
	*x = ListItemSalesStatsRequest{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemSalesStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemSalesStatsRequest) ProtoMessage() {}

func (x *ListItemSalesStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemSalesStatsRequest.ProtoReflect.Descriptor instead.
func (*ListItemSalesStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemSalesStatsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemSalesStatsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListItemSalesStatsRequest) GetItemNameQuery() string {
	if x != nil && x.ItemNameQuery != nil {
		return *x.ItemNameQuery
	}
	return ""
}

func (x *ListItemSalesStatsRequest) GetWearName() string {
	if x != nil && x.WearName != nil {
		return *x.WearName
	}
	return ""
}

func (x *ListItemSalesStatsRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListItemSalesStatsRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListItemSalesStatsRequest) GetSoldFrom() string {
	if x != nil && x.SoldFrom != nil {
		return *x.SoldFrom
	}
	return ""
}

func (x *ListItemSalesStatsRequest) GetSoldTo() string {
	if x != nil && x.SoldTo != nil {
		return *x.SoldTo
	}
	return ""
}

func (x *ListItemSalesStatsRequest) GetMinSalesCount() int64 {
	if x != nil && x.MinSalesCount != nil {
		return *x.MinSalesCount
	}
	return 0
}

type ItemSalesStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemWearId    int64                  `protobuf:"varint,3,opt,name=item_wear_id,json=itemWearId,proto3" json:"item_wear_id,omitempty"`
	WearName      string                 `protobuf:"bytes,4,opt,name=wear_name,json=wearName,proto3" json:"wear_name,omitempty"`
	SalesCount    int64                  `protobuf:"varint,5,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,6,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	MedianPrice   float64                `protobuf:"fixed64,7,opt,name=median_price,json=medianPrice,proto3" json:"median_price,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,8,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,9,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	SoldPrices    []float64              `protobuf:"fixed64,10,rep,packed,name=sold_prices,json=soldPrices,proto3" json:"sold_prices,omitempty"`
	FirstSoldOn   string                 `protobuf:"bytes,11,opt,name=first_sold_on,json=firstSoldOn,proto3" json:"first_sold_on,omitempty"`
	LastSoldOn    string                 `protobuf:"bytes,12,opt,name=last_sold_on,json=lastSoldOn,proto3" json:"last_sold_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSalesStats) Reset() {
	*x = ItemSalesStats{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSalesStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSalesStats) ProtoMessage() {}

func (x *ItemSalesStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSalesStats.ProtoReflect.Descriptor instead.
func (*ItemSalesStats) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{4}
}

func (x *ItemSalesStats) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemSalesStats) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemSalesStats) GetItemWearId() int64 {
	if x != nil {
		return x.ItemWearId
	}
	return 0
}

func (x *ItemSalesStats) GetWearName() string {
	if x != nil {
		return x.WearName
	}
	return ""
}

func (x *ItemSalesStats) GetSalesCount() int64 {
	if x != nil {
		return x.SalesCount
	}
	return 0
}

func (x *ItemSalesStats) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *ItemSalesStats) GetMedianPrice() float64 {
	if x != nil {
		return x.MedianPrice
	}
	return 0
}

func (x *ItemSalesStats) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ItemSalesStats) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ItemSalesStats) GetSoldPrices() []float64 {
	if x != nil {
		return x.SoldPrices
	}
	return nil
}

func (x *ItemSalesStats) GetFirstSoldOn() string {
	if x != nil {
		return x.FirstSoldOn
	}
	return ""
}

func (x *ItemSalesStats) GetLastSoldOn() string {
	if x != nil {
		return x.LastSoldOn
	}
	return ""
}

type ListItemSalesStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemSalesStats      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemSalesStatsResponse) Reset() {
	*x = ListItemSalesStatsResponse{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemSalesStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemSalesStatsResponse) ProtoMessage() {}

func (x *ListItemSalesStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemSalesStatsResponse.ProtoReflect.Descriptor instead.
func (*ListItemSalesStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{5}
}

func (x *ListItemSalesStatsResponse) GetItems() []*ItemSalesStats {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemSalesStatsResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemSalesStatsResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListItemSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ItemNameQuery *string                `protobuf:"bytes,3,opt,name=item_name_query,json=itemNameQuery,proto3,oneof" json:"item_name_query,omitempty"`
	WearName      *string                `protobuf:"bytes,4,opt,name=wear_name,json=wearName,proto3,oneof" json:"wear_name,omitempty"`
	ItemWearId    *int64                 `protobuf:"varint,5,opt,name=item_wear_id,json=itemWearId,proto3,oneof" json:"item_wear_id,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,6,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,7,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	SoldFrom      *string                `protobuf:"bytes,8,opt,name=sold_from,json=soldFrom,proto3,oneof" json:"sold_from,omitempty"`
	SoldTo        *string                `protobuf:"bytes,9,opt,name=sold_to,json=soldTo,proto3,oneof" json:"sold_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemSalesRequest) Reset() {
	*x = ListItemSalesRequest{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemSalesRequest) ProtoMessage() {}

func (x *ListItemSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemSalesRequest.ProtoReflect.Descriptor instead.
func (*ListItemSalesRequest) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{6}
}

func (x *ListItemSalesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemSalesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListItemSalesRequest) GetItemNameQuery() string {
	if x != nil && x.ItemNameQuery != nil {
		return *x.ItemNameQuery
	}
	return ""
}

func (x *ListItemSalesRequest) GetWearName() string {
	if x != nil && x.WearName != nil {
		return *x.WearName
	}
	return ""
}

func (x *ListItemSalesRequest) GetItemWearId() int64 {
	if x != nil && x.ItemWearId != nil {
		return *x.ItemWearId
	}
	return 0
}

func (x *ListItemSalesRequest) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListItemSalesRequest) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListItemSalesRequest) GetSoldFrom() string {
	if x != nil && x.SoldFrom != nil {
		return *x.SoldFrom
	}
	return ""
}

func (x *ListItemSalesRequest) GetSoldTo() string {
	if x != nil && x.SoldTo != nil {
		return *x.SoldTo
	}
	return ""
}

type ItemSale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	WearName      string                 `protobuf:"bytes,2,opt,name=wear_name,json=wearName,proto3" json:"wear_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	WearValue     float64                `protobuf:"fixed64,4,opt,name=wear_value,json=wearValue,proto3" json:"wear_value,omitempty"`
	SoldOn        string                 `protobuf:"bytes,5,opt,name=sold_on,json=soldOn,proto3" json:"sold_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSale) Reset() {
	*x = ItemSale{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSale) ProtoMessage() {}

func (x *ItemSale) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSale.ProtoReflect.Descriptor instead.
func (*ItemSale) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{7}
}

func (x *ItemSale) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ItemSale) GetWearName() string {
	if x != nil {
		return x.WearName
	}
	return ""
}

func (x *ItemSale) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemSale) GetWearValue() float64 {
	if x != nil {
		return x.WearValue
	}
	return 0
}

func (x *ItemSale) GetSoldOn() string {
	if x != nil {
		return x.SoldOn
	}
	return ""
}

type ListItemSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemSale            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemSalesResponse) Reset() {
	*x = ListItemSalesResponse{}
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemSalesResponse) ProtoMessage() {}

func (x *ListItemSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parsing_v1_parsing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemSalesResponse.ProtoReflect.Descriptor instead.
func (*ListItemSalesResponse) Descriptor() ([]byte, []int) {
	return file_proto_parsing_v1_parsing_proto_rawDescGZIP(), []int{8}
}

func (x *ListItemSalesResponse) GetItems() []*ItemSale {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemSalesResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemSalesResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_proto_parsing_v1_parsing_proto protoreflect.FileDescriptor

const file_proto_parsing_v1_parsing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/parsing/v1/parsing.proto\x12\n" +
	"parsing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x04\n" +
	"\x11ListOffersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x19\n" +
	"\x05state\x18\x03 \x01(\x03H\x00R\x05state\x88\x01\x01\x12\x1a\n" +
	"\x06app_id\x18\x04 \x01(\x03H\x01R\x05appId\x88\x01\x01\x12\"\n" +
	"\n" +
	"name_query\x18\x05 \x01(\tH\x02R\tnameQuery\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x06 \x01(\x01H\x03R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\a \x01(\x01H\x04R\bmaxPrice\x88\x01\x01\x12<\n" +
	"\tlist_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x05R\blistTime\x88\x01\x01\x12B\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vlastUpdated\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\n" +
	" \x01(\tH\aR\x06sortBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\v \x01(\tH\bR\tsortOrder\x88\x01\x01B\b\n" +
	"\x06_stateB\t\n" +
	"\a_app_idB\r\n" +
	"\v_name_queryB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\f\n" +
	"\n" +
	"_list_timeB\x0f\n" +
	"\r_last_updatedB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"\xfe\x04\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1e\n" +
	"\n" +
	"commission\x18\x03 \x01(\x01R\n" +
	"commission\x12\x10\n" +
	"\x03tax\x18\x04 \x01(\x01R\x03tax\x12\x19\n" +
	"\bclass_id\x18\x05 \x01(\tR\aclassId\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06app_id\x18\a \x01(\x03R\x05appId\x12\x1d\n" +
	"\n" +
	"context_id\x18\b \x01(\tR\tcontextId\x12\x19\n" +
	"\basset_id\x18\t \x01(\tR\aassetId\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x19\n" +
	"\boffer_id\x18\v \x01(\tR\aofferId\x12\x14\n" +
	"\x05state\x18\f \x01(\x03R\x05state\x12B\n" +
	"\x0fescrow_end_date\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rescrowEndDate\x127\n" +
	"\tlist_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blistTime\x12=\n" +
	"\flast_updated\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x12\n" +
	"\x04wear\x18\x10 \x01(\x01R\x04wear\x12\x12\n" +
	"\x04txid\x18\x11 \x01(\tR\x04txid\x12!\n" +
	"\ftrade_locked\x18\x12 \x01(\bR\vtradeLocked\x12\x16\n" +
	"\x06addons\x18\x13 \x03(\tR\x06addons\x12,\n" +
	"\x12buyer_country_code\x18\x14 \x01(\tR\x10buyerCountryCode\"\x81\x01\n" +
	"\x12ListOffersResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.parsing.v1.OfferR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"\xb5\x03\n" +
	"\x19ListItemSalesStatsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12+\n" +
	"\x0fitem_name_query\x18\x03 \x01(\tH\x00R\ritemNameQuery\x88\x01\x01\x12 \n" +
	"\twear_name\x18\x04 \x01(\tH\x01R\bwearName\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x01H\x02R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x01H\x03R\bmaxPrice\x88\x01\x01\x12 \n" +
	"\tsold_from\x18\a \x01(\tH\x04R\bsoldFrom\x88\x01\x01\x12\x1c\n" +
	"\asold_to\x18\b \x01(\tH\x05R\x06soldTo\x88\x01\x01\x12+\n" +
	"\x0fmin_sales_count\x18\t \x01(\x03H\x06R\rminSalesCount\x88\x01\x01B\x12\n" +
	"\x10_item_name_queryB\f\n" +
	"\n" +
	"_wear_nameB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\f\n" +
	"\n" +
	"_sold_fromB\n" +
	"\n" +
	"\b_sold_toB\x12\n" +
	"\x10_min_sales_count\"\x87\x03\n" +
	"\x0eItemSalesStats\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12 \n" +
	"\fitem_wear_id\x18\x03 \x01(\x03R\n" +
	"itemWearId\x12\x1b\n" +
	"\twear_name\x18\x04 \x01(\tR\bwearName\x12\x1f\n" +
	"\vsales_count\x18\x05 \x01(\x03R\n" +
	"salesCount\x12\x1b\n" +
	"\tavg_price\x18\x06 \x01(\x01R\bavgPrice\x12!\n" +
	"\fmedian_price\x18\a \x01(\x01R\vmedianPrice\x12\x1b\n" +
	"\tmin_price\x18\b \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\t \x01(\x01R\bmaxPrice\x12\x1f\n" +
	"\vsold_prices\x18\n" +
	" \x03(\x01R\n" +
	"soldPrices\x12\"\n" +
	"\rfirst_sold_on\x18\v \x01(\tR\vfirstSoldOn\x12 \n" +
	"\flast_sold_on\x18\f \x01(\tR\n" +
	"lastSoldOn\"|\n" +
	"\x1aListItemSalesStatsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.parsing.v1.ItemSalesStatsR\x05items\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xa7\x03\n" +
	"\x14ListItemSalesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12+\n" +
	"\x0fitem_name_query\x18\x03 \x01(\tH\x00R\ritemNameQuery\x88\x01\x01\x12 \n" +
	"\twear_name\x18\x04 \x01(\tH\x01R\bwearName\x88\x01\x01\x12%\n" +
	"\fitem_wear_id\x18\x05 \x01(\x03H\x02R\n" +
	"itemWearId\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x06 \x01(\x01H\x03R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\a \x01(\x01H\x04R\bmaxPrice\x88\x01\x01\x12 \n" +
	"\tsold_from\x18\b \x01(\tH\x05R\bsoldFrom\x88\x01\x01\x12\x1c\n" +
	"\asold_to\x18\t \x01(\tH\x06R\x06soldTo\x88\x01\x01B\x12\n" +
	"\x10_item_name_queryB\f\n" +
	"\n" +
	"_wear_nameB\x0f\n" +
	"\r_item_wear_idB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\f\n" +
	"\n" +
	"_sold_fromB\n" +
	"\n" +
	"\b_sold_to\"\x92\x01\n" +
	"\bItemSale\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1b\n" +
	"\twear_name\x18\x02 \x01(\tR\bwearName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"wear_value\x18\x04 \x01(\x01R\twearValue\x12\x17\n" +
	"\asold_on\x18\x05 \x01(\tR\x06soldOn\"q\n" +
	"\x15ListItemSalesResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.parsing.v1.ItemSaleR\x05items\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset2\x98\x02\n" +
	"\x0eParsingService\x12K\n" +
	"\n" +
	"ListOffers\x12\x1d.parsing.v1.ListOffersRequest\x1a\x1e.parsing.v1.ListOffersResponse\x12c\n" +
	"\x12ListItemSalesStats\x12%.parsing.v1.ListItemSalesStatsRequest\x1a&.parsing.v1.ListItemSalesStatsResponse\x12T\n" +
	"\rListItemSales\x12 .parsing.v1.ListItemSalesRequest\x1a!.parsing.v1.ListItemSalesResponseB/Z-skinbaron-analyzer/proto/parsing/v1;parsingv1b\x06proto3"

var (
	file_proto_parsing_v1_parsing_proto_rawDescOnce sync.Once
	file_proto_parsing_v1_parsing_proto_rawDescData []byte
)

func file_proto_parsing_v1_parsing_proto_rawDescGZIP() []byte {
	file_proto_parsing_v1_parsing_proto_rawDescOnce.Do(func() {
		file_proto_parsing_v1_parsing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parsing_v1_parsing_proto_rawDesc), len(file_proto_parsing_v1_parsing_proto_rawDesc)))
	})
	return file_proto_parsing_v1_parsing_proto_rawDescData
}

var file_proto_parsing_v1_parsing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_parsing_v1_parsing_proto_goTypes = []any{
	(*ListOffersRequest)(nil),          // 0: parsing.v1.ListOffersRequest
	(*Offer)(nil),                      // 1: parsing.v1.Offer
	(*ListOffersResponse)(nil),         // 2: parsing.v1.ListOffersResponse
	(*ListItemSalesStatsRequest)(nil),  // 3: parsing.v1.ListItemSalesStatsRequest
	(*ItemSalesStats)(nil),             // 4: parsing.v1.ItemSalesStats
	(*ListItemSalesStatsResponse)(nil), // 5: parsing.v1.ListItemSalesStatsResponse
	(*ListItemSalesRequest)(nil),       // 6: parsing.v1.ListItemSalesRequest
	(*ItemSale)(nil),                   // 7: parsing.v1.ItemSale
	(*ListItemSalesResponse)(nil),      // 8: parsing.v1.ListItemSalesResponse
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_proto_parsing_v1_parsing_proto_depIdxs = []int32{
	9,  // 0: parsing.v1.ListOffersRequest.list_time:type_name -> google.protobuf.Timestamp
	9,  // 1: parsing.v1.ListOffersRequest.last_updated:type_name -> google.protobuf.Timestamp
	9,  // 2: parsing.v1.Offer.escrow_end_date:type_name -> google.protobuf.Timestamp
	9,  // 3: parsing.v1.Offer.list_time:type_name -> google.protobuf.Timestamp
	9,  // 4: parsing.v1.Offer.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 5: parsing.v1.ListOffersResponse.items:type_name -> parsing.v1.Offer
	4,  // 6: parsing.v1.ListItemSalesStatsResponse.items:type_name -> parsing.v1.ItemSalesStats
	7,  // 7: parsing.v1.ListItemSalesResponse.items:type_name -> parsing.v1.ItemSale
	0,  // 8: parsing.v1.ParsingService.ListOffers:input_type -> parsing.v1.ListOffersRequest
	3,  // 9: parsing.v1.ParsingService.ListItemSalesStats:input_type -> parsing.v1.ListItemSalesStatsRequest
	6,  // 10: parsing.v1.ParsingService.ListItemSales:input_type -> parsing.v1.ListItemSalesRequest
	2,  // 11: parsing.v1.ParsingService.ListOffers:output_type -> parsing.v1.ListOffersResponse
	5,  // 12: parsing.v1.ParsingService.ListItemSalesStats:output_type -> parsing.v1.ListItemSalesStatsResponse
	8,  // 13: parsing.v1.ParsingService.ListItemSales:output_type -> parsing.v1.ListItemSalesResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_parsing_v1_parsing_proto_init() }
func file_proto_parsing_v1_parsing_proto_init() {
	if File_proto_parsing_v1_parsing_proto != nil {
		return
	}
	file_proto_parsing_v1_parsing_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_parsing_v1_parsing_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_parsing_v1_parsing_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parsing_v1_parsing_proto_rawDesc), len(file_proto_parsing_v1_parsing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parsing_v1_parsing_proto_goTypes,
		DependencyIndexes: file_proto_parsing_v1_parsing_proto_depIdxs,
		MessageInfos:      file_proto_parsing_v1_parsing_proto_msgTypes,
	}.Build()
	File_proto_parsing_v1_parsing_proto = out.File
	file_proto_parsing_v1_parsing_proto_goTypes = nil
	file_proto_parsing_v1_parsing_proto_depIdxs = nil
}
